Update compile_generics.yml

diff --git a/.github/workflows/compile_generics.yml b/.github/workflows/compile_generics.yml
--- a/.github/workflows/compile_generics.yml
+++ b/.github/workflows/compile_generics.yml
@@ -175,13 +175,32 @@ jobs:
           echo "secret_access_key = $R2_SECRET_KEY" >> ~/.config/rclone/rclone.conf
           echo "endpoint = https://fb5f7d31bedfe4f3538ddfa6db491962.r2.cloudflarestorage.com" >> ~/.config/rclone/rclone.conf
           
+      - name: Acquire Mutex Lock
+        uses: crazy-max/ghaction-mutex@v1
+        with:
+          mutex: cloudflare-upload-lock
+          timeout: 3000
+
       - name: Upload Artifacts to Cloudflare R2
         env:
           R2_BUCKET: "spooksapi"
           R2_PATH: "GhostESPBins"
         run: |
+          echo "Uploading ${{ matrix.target.zip_name }} to Cloudflare R2..."
           rclone copy "packaged_artifacts/${{ matrix.target.zip_name }}" "cloudflare_r2:${R2_BUCKET}/${R2_PATH}" --progress
+          if [ $? -ne 0 ]; then
+            echo "Upload failed. Exiting..."
+            exit 1
+          fi
+          echo "Upload of ${{ matrix.target.zip_name }} to Cloudflare R2 completed successfully."
 
+      - name: Release Mutex Lock
+        uses: crazy-max/ghaction-mutex@v1
+        with:
+          mutex: cloudflare-upload-lock
+          release: true
+
+      
       - name: Notify Discord of Successful Release
         if: success()
         env:
