Update compile_generics.yml

diff --git a/.github/workflows/compile_generics.yml b/.github/workflows/compile_generics.yml
--- a/.github/workflows/compile_generics.yml
+++ b/.github/workflows/compile_generics.yml
@@ -79,6 +79,11 @@ jobs:
           export IDF_TARGET=${{ matrix.target.idf_target }}
           echo "IDF_TARGET is set to $IDF_TARGET"
 
+      - name: Verify SDK Config Options
+        run: |
+          echo "Checking for Display Options in $DEST_FILE"
+          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" "$DEST_FILE" || echo "One or more options not found in $DEST_FILE"
+
       - name: Build Project
         run: |
           . ~/esp-idf/export.sh
