Update compile_generics.yml

diff --git a/.github/workflows/compile_generics.yml b/.github/workflows/compile_generics.yml
--- a/.github/workflows/compile_generics.yml
+++ b/.github/workflows/compile_generics.yml
@@ -61,14 +61,7 @@ jobs:
 
       - name: Apply Custom SDK Config
         run: |
-          DEST_FILE="sdkconfig"
-          echo "Applying SDK Config: ${{ matrix.target.sdkconfig_file }} to $DEST_FILE"
-          if [ -f "${{ matrix.target.sdkconfig_file }}" ]; then
-            cp "${{ matrix.target.sdkconfig_file }}" "$DEST_FILE"
-          else
-            echo "Error: Source config file ${{ matrix.target.sdkconfig_file }} does not exist."
-            exit 1
-          fi
+          cp "${{ matrix.target.sdkconfig_file }}" sdkconfig.defaults
 
       - name: Set up ESP-IDF and Target
         run: |
@@ -80,11 +73,8 @@ jobs:
 
       - name: Verify SDK Config Options
         run: |
-          DEST_FILE="sdkconfig"
-          echo "Checking for Display Options in $DEST_FILE"
-          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" "$DEST_FILE" || echo "One or more options not found in $DEST_FILE"
-          chmod 444 sdkconfig
-          echo "Locked sdkconfig to prevent overwriting."
+          echo "Checking if configurations exist in sdkconfig.defaults"
+          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" sdkconfig.defaults || echo "One or more options not found in sdkconfig.defaults"
 
       - name: Build Project
         run: |
@@ -93,11 +83,8 @@ jobs:
 
       - name: Verify SDK Config Options
         run: |
-          DEST_FILE="sdkconfig"
-          echo "Checking for Display Options in $DEST_FILE"
-          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" "$DEST_FILE" || echo "One or more options not found in $DEST_FILE"
-          chmod 444 sdkconfig
-          echo "Locked sdkconfig to prevent overwriting."
+          echo "Checking if configurations exist in sdkconfig.defaults"
+          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" sdkconfig.defaults || echo "One or more options not found in sdkconfig.defaults"
 
       - name: Download Correct Bootloader
         run: |
