Update compile_generics.yml

diff --git a/.github/workflows/compile_generics.yml b/.github/workflows/compile_generics.yml
--- a/.github/workflows/compile_generics.yml
+++ b/.github/workflows/compile_generics.yml
@@ -83,11 +83,21 @@ jobs:
           DEST_FILE="sdkconfig"
           echo "Checking for Display Options in $DEST_FILE"
           grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" "$DEST_FILE" || echo "One or more options not found in $DEST_FILE"
+          chmod 444 sdkconfig
+          echo "Locked sdkconfig to prevent overwriting."
 
       - name: Build Project
         run: |
           . ~/esp-idf/export.sh
           idf.py build
+
+      - name: Verify SDK Config Options
+        run: |
+          DEST_FILE="sdkconfig"
+          echo "Checking for Display Options in $DEST_FILE"
+          grep -E "CONFIG_WITH_SCREEN|CONFIG_TFT_WIDTH|CONFIG_TFT_HEIGHT|CONFIG_USE_TOUCHSCREEN|CONFIG_USE_JOYSTICK|CONFIG_USE_CARDPUTER|CONFIG_IS_GHOST_BOARD|CONFIG_USE_7_INCHER|CONFIG_Waveshare_LCD|CONFIG_Crowtech_LCD|CONFIG_Sunton_LCD|CONFIG_USE_ILI9341_2" "$DEST_FILE" || echo "One or more options not found in $DEST_FILE"
+          chmod 444 sdkconfig
+          echo "Locked sdkconfig to prevent overwriting."
 
       - name: Download Correct Bootloader
         run: |
